# Generated by Django 5.1.7 on 2026-02-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('cost_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=45)),
                ('manufacturer', models.CharField(max_length=45)),
                ('dosage_form', models.CharField(max_length=45)),
            ],
        ),
    ]
