# Generated by Django 5.1.7 on 2026-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='cost_per_piece',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False),
        ),
    ]
