# Generated by Django 5.1.7 on 2026-02-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('pharmacy_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=45)),
                ('pincode', models.IntegerField()),
                ('contact', models.CharField(max_length=45)),
            ],
        ),
    ]
