# Generated by Django 5.1.7 on 2026-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_id',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False),
        ),
    ]
