# Generated by Django 5.1.7 on 2026-02-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_alter_pharmacy_pharmacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
