# Generated by Django 5.1.7 on 2026-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_latitude_pharmacy_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
