# Generated by Django 5.1.7 on 2026-02-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacy_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
