# Generated by Django 5.1.7 on 2026-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_latitude_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
