# Generated by Django 5.1.7 on 2026-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
