# Generated by Django 5.1.7 on 2026-02-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_remove_hospital_address_remove_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='location',
        ),
    ]
