# Generated by Django 5.1.7 on 2026-02-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Hospital',
            fields=[
                ('doctor_instance_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fees', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('working_hours', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization')),
            ],
        ),
    ]
