# Generated by Django 5.1.7 on 2026-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_associations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_hospital',
            name='doctor_instance_id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
