# Generated by Django 5.1.7 on 2026-02-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_associations', '0002_alter_doctor_hospital_doctor_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_hospital',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
