# Generated by Django 5.1.7 on 2026-02-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_associations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoints',
            fields=[
                ('appointment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token_no', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('doctor_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_associations.doctor_hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
