# Generated by Django 5.1.7 on 2026-02-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoints',
            name='token_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
