# Generated by Django 5.1.7 on 2026-02-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appoints_token_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoints',
            name='status',
        ),
    ]
