# Generated by Django 5.1.7 on 2026-02-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appoints_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoints',
            old_name='patient',
            new_name='patient_contact',
        ),
    ]
