# Generated by Django 5.1.7 on 2026-02-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_patient_appoints_patient_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoints',
            name='reason_for_visit',
        ),
        migrations.AddField(
            model_name='appoints',
            name='urgency_score',
            field=models.IntegerField(default=1),
        ),
    ]
