# Generated by Django 5.1.7 on 2026-02-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appoints_reason_for_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoints',
            name='appointment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
