# Generated by Django 5.1.7 on 2026-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
