# Generated by Django 5.1.7 on 2026-02-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=45)),
            ],
        ),
    ]
