# Generated by Django 5.1.7 on 2026-02-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('pharmacy_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy_medicine',
            name='manufacturer',
            field=models.ForeignKey(default='M1', on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacy_medicine',
            name='medicine_instance_id',
            field=models.CharField(blank=True, max_length=45, primary_key=True, serialize=False),
        ),
    ]
