# Generated by Django 5.1.7 on 2026-02-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('mobileno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
